name = "backend-empleados"
type = "python"
main = "main.py"
compatibility_flags = ["python_workers"]

[env.production]
name = "backend-empleados-prod"

[build]
command = "pip install -r requirements.txt"
